--- #YAML:1.0
name:                User-Simple
version:             1.38
abstract:            Simple user sessions management
license:             perl
author:              
    - Gunnar Wolf <gwolf@gwolf.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Calc:                    0
    DBI:                           0
    Digest::MD5:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
